name: Github Page Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'metrics/**'
      - 'cmd/web/**'
      - 'internal/web/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

env:
  go-version: '1.25'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.go-version }}

      - name: Build the web
        run: make web-build

      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
