name: Daily Extraction

on:
  schedule:
    - cron: "0 6 * * *" # Run the workflow every day at 6 AM UTC
  workflow_dispatch:

env:
  py-version: '3.12'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ env.py-version }}

      - name: Install dependencies
        run: make install

      - name: Create credentials.json
        run: |
          echo '${{ secrets.CREDENTIALS }}' > credentials.json

      - name: Verify credentials.json
        run: |
          if [ -f credentials.json ]; then
            echo "Credentials file exists."
          else
            echo "Credentials file not found."
            exit 1
          fi

      - name: Run Python script
        id: generate-log
        run: |
          .venv/bin/python script/main.py
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}

      - name: Clean up credentials.json
        run: rm -f credentials.json
