name: Ruff Formatting

on:
  pull_request:
    branches: [main]
    paths: [main.py, utils/**]
  push:
    branches: [main]
    paths: [main.py, utils/**]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make init

      - name: Run Ruff formatter
        run: |
          make format

      - name: Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "ci: auto-format code with Ruff"
            git push orign HEAD:${{ github.head_ref }}
          fi
