name: Daily Extraction Schedule

on:
  schedule:
    # Run the workflow every day at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make init

      - name: Run Python script
        run: make run
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
